# Generated by Django 5.2.11 on 2026-02-15 11:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('raw_input', models.TextField()),
                ('ai_response', models.JSONField(default=dict)),
                ('patient_summary', models.TextField(blank=True, null=True)),
                ('chief_complaint', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SBARReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('transcription', models.TextField()),
                ('ai_response', models.JSONField(default=dict)),
                ('patient_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
